### ISSUE TITLE
Team

### ISSUE THREAD

**Issue by prabuvenkat** [prabuvenkat/dc-issues#19]
- Should there be information about current team ? If yes, need list.

**Comment by ravidalit** [comment]
I am thinking of keeping the team private for the time being. Even the last time we gave a list of team members and only few were working. So, thinking of waiting for few weeks, after the website is launched to decide of members.

**Comment by ArchanaRajvir** [comment]
I agree with Ravi. I personally feel we should not disclose the team as it is often fluid and volunteer based. If ever there evolves a stable core team over the time then this can be considered. But for now, we can just mention Ravi's name as the founder in about us page.

**Comment by prabuvenkat** [comment]
Removed team-box from the About page. Instead, playlists referenced in the About page are embedded alongside the text.
