### ISSUE TITLE
Modify main navbar (via Ravi, Samata, Gee, Murali)

### ISSUE THREAD

**Issue by prabuvenkat** [prabuvenkat/dc-issues#2]
(via Ravi) News, Topics, Features, Channel, Documentary, Album, Documents [anyother thing you can add or remove], Media

**Comment by prabuvenkat** [comment]
1. Submissions will go inside the Contact Us page
2. Topics will go under About page

**Comment by prabuvenkat** [comment]
Documents : not providing this for the moment.. some thoughts:

Who will this be for ? if it is going to be internal and mainly for DC team, it is probably better with something like a dropbox account. if it is for public, we could probably organize it better through articles/or even a mini-feature with some information around the specific content. 

On a related note, all approved user-submitted content should automatically become some sort of a published post type. User submitted content that is not approved could be moved to a drop-box like location (PS: for future; not for now).

**Comment by dharmaTj** [comment]
Hi Prabu
Summing up my email about the buttons in the main navigation bar:
1. Dalit Camera logo (which is also a button to home-page)
2. 'HOME' (just to be more explicit and clear)
3. 'FEATURES' or 'ARTICLES' or simply 'BLOG' (a seamless list of all write-ups in full. Just
     like in here: https://hiredknaves.wordpress.com/)
4. 'VIDEO CHANNEL'
5. 'DALIT CAMERA IN NEWS'
6. 'ABOUT' & 'CONTACT US' (they are fine above the logo, as you designed)
7. 'DOCUMENTS ARCHIVE' (legal documents and more for users to download)
8. 'RESOURCES' (Adding this now. To link other resources with shared politics like RTI, Dalit 
     History Month, and many more)

Is it possible for the webpage to cover the entire screen, without the current half-inch grey coloured gaps on both sides?

While talking to Ravi yesterday, he was suggesting that the home-page should direct the first attention of a visitor to the written content alone. So I suggested that the videos list on the left-hand side in my template can be made horizontal and moved to the bottom of the page (like the 'EXCLUSIVES' you designed on the current home-page)

**Comment by prabuvenkat** [comment]
Final Website Structure for v1.0:

## Primary Menu

1. **Home**
2. **Features** : everything goes here -- specific types (transcripts, articles, announcements, event-photo-gallery, etc marked as categories)
3. **YouTube Channel**
4. **Magazine** (link to flyer now; to actual magazine when it goes on-air)
5. **Gallery** (like youtube channel, gallery content will be sourced from an external site, for eg., flickr)  
6. **Resources**
    - _Downloads_ (files will *not* be hosted on the wordpress site, but only listed)
    - _Links_

## Top Menu

1. **About**
2. **Info**
    - (topics)
    - (Team : if we want to list members)
    - DC in News
3. **Contact Us**
    - submissions
    -  (primary contact details : email/telephones)
