### ISSUE TITLE
Switch to new logo

### ISSUE THREAD

**Issue by prabuvenkat** [prabuvenkat/dc-issues#21]

**Comment by ravidalit** [comment]
![dcthumbnail](https://cloud.githubusercontent.com/assets/19575097/15547263/b069e008-22c0-11e6-851b-ccb2e3c0b594.gif)

attaching the original DC Logo

**Comment by ravidalit** [comment]
![dclogo1](https://cloud.githubusercontent.com/assets/19575097/15547324/ec955b98-22c0-11e6-8be9-f615dcfd9f48.gif)

**Comment by ArchanaRajvir** [comment]
Ravi,
Isn't the one on [DalitCamera's FB page the new logo](https://www.facebook.com/DalitCameraThroughUnTouchableEyes/photos/a.414266131965647.93464.414265715299022/414266135298980/?type=3&theater) ? 

We need to have the logo consistent across platforms. So which one will be go ahead with?

arch!

**Comment by ravidalit** [comment]
Hi

FB is not the new logo, the file I sent you was thumbnail and the fb page did not accept. Across Youtube videos, the logo I sent you earlier is used.
