### ISSUE TITLE
Magazine flyer

### ISSUE THREAD

**Issue by prabuvenkat** [prabuvenkat/dc-issues#24]
Require "coming soon" content. I can design a flyer.

**Comment by ravidalit** [comment]
Here is the content thought about, it has not taken off.
Time line of the Event of Rohit Vemula with documents 

---Dharma Teja (29th of April)

2. Story of Radika

----Dharma Teja (29th of April)

(The above story will also cover documents, Rohit suicide note, administration communication, HRD letter, Conversion to Buddhism)

3. Media's Role

----Story of the Media in making it a National issue

(Nidhin)

---Story of the movement

(Nikila) (24th April)


----Story of the movement in Delhi

(Deepti Sreeram)


4. Designing the magazine and the cover picture

--Achu

**Comment by dharmaTj** [comment]
Hi Prabu. No need for a flyer I think. Just write 'coming soon' or 'watch this space' or you can even remove the tab and add it only after the magazine is available.

**Comment by prabuvenkat** [comment]
Magazine link is removed from the main navigation bar. Will be re-added later when we are ready.
